### PR TITLE
Final Changes to Rolling Regression

### PR DESCRIPTION
**Pull request by derekholste**
1. Adding in the Output for the Rolling Regression in the MD. file

2. Deleting Rolling Regression from the Non existant page

### CODE REVIEW

**Comment by aeturrell** [comment]
Something funny has happened here with, for example, the introduction parts repeated under the R section. There seem to be a lot of changes beyond adding output to the R section too.

**Comment by aeturrell** [comment]
@derekholste I've put your changes in the rolling regression through in d41a204. Please can you check them? If you're happy, remove changes to the rolling regression page in this pull request and just put through the change to the non-existent pages.

**Comment by derekholste** [comment]
Yes that looks good thank you. Originally the output for the last lines of code did not show so I fixed that. Sorry if there were other issues.

**Comment by derekholste** [comment]
I have now deleted the extra introduction section.

**Comment by NickCH-K** [comment]
Just so I'm following, are the intended changes now already included via @aeturrell 's commit, or are there other changes I need to merge in here besides the changes to Desired Nonexistent Pages? (if it's just the latter I might do that on a different push to avoid conflicts)

**Comment by derekholste** [comment]
There are also changed other than the non-existent page. When adding in the output I accidentally added in another introduction and then deleted it. The most recent pull request that I modified should include everything from @aeturrell 's comment. Thank you.

**Pull request merged**
