### PR TITLE
Added seaborn.objects line styling code to page needing more languages to it,

### PR DESCRIPTION
**Pull request by RommelArtola**

### CODE REVIEW

**Comment by NickCH-K** [comment]
This is great! Do you think you could drop the part about reassigning the year x-axis? We try to keep examples fairly short and focused on the task being described on the page.

**Comment by RommelArtola** [comment]
Certainly! I imagine you just mean in regards to the docstring, or the dataframe manipulation altogether?

If the former, absolutely. If the latter, definitely still possible but the xaxis just shows to ticks for two years (like 1980 and 2020, for example) out of the entire range. Couldn’t figure out how to add more xticks on it since it’s a date data type and not a numeric that can be achieved with so.Continous(), for example.

I can give it another shot after I’m home from work today again, and just have it show the default xticks if I can’t get it.
________________________________

**Comment by RommelArtola** [comment]
Dataframe is no longer aggregated and the xtick labeling for dates (temporal) was found and added

**Comment by NickCH-K** [comment]
Great, thank you! Sorry I didn't come to this sooner, I could have pointed you to `so.Temporal()` (IMO got a little fancy on the naming with this one, coulda just been Date)

**Pull request merged**
