### PR TITLE
Update Scatterplots.md

### PR DESCRIPTION
**Pull request by RommelArtola**
Added a small bit about doing the same seaborn scatterplot in a seaborn.object plot with some added things like renaming the plot, and setting the theme to all white to get started. Also added a linear fit line so users can play with it and see the art of the possible with it! Trying to figure out how to add the photo now to this locked repo using plot.save('seaborn_objects_scatter.png', bbox_inches='tight')

### CODE REVIEW

**Comment by NickCH-K** [comment]
This is great! As for adding the file, if you're familiar with GitHub you can do a fork/pull request. If not, upload it here and I can add the file.

**Comment by RommelArtola** [comment]
I think I added it now! Should be under a new PR

**Comment by NickCH-K** [comment]
Hmm, I don't see it

**Comment by RommelArtola** [comment]
Still missing? Maybe I'm even worse at Github than I thought lol. Pasted what I thought was the successful PR below, but also attaching the plot to the email reply.

[cid:6e527877-84d7-48fa-a25d-2988061617df]
________________________________

**Comment by NickCH-K** [comment]
I see it now, just merged that one in. Running the checks on this one now.

**Comment by RommelArtola** [comment]
Wohoo! Thanks professor!
________________________________

**Pull request merged**
