### PR TITLE
Upgrade to Jekyll 4 and move to GH Actions

### PR DESCRIPTION
**Pull request by khwilson**
Security warnings about `kramdown` prompted an upgrade to Jekyll 4.
The main issue here is a series of version bumps and (maybe necessary?)
some explicit mentions of plugins in the `_config.yml` .

One benefit: my custom edit link code is now unnecessary as the upstream
`just-the-docs` template has a good enough implementation. Hooray!
So we move to the current gem. Note the version pin.

The other move here is to move away from CircleCI (which currently,
I think, I'm the only one who can access haha) and instead use Github
Actions, which will make long term maintenance easier.

While we're here, we also removed some extraneous R and Mac cruft.

### CODE REVIEW

**Comment by NickCH-K** [comment]
I don't really know anything about this, but it sounds good to me! It does say that it failed the circleci checks.

**Comment by khwilson** [comment]
It should fail the circle ci checks because thhis moves to GH Actions. I'll disable CircleCI when this gets merged.

OK, I'll merge this and it should redeploy. I won't switch the branch names right now because it would mess up everybody's local pulls. :-)

**Comment by grantmcdermott** [comment]
Late to the party, but thanks for taking care of this K!

**Comment by khwilson** [comment]
Going down my list of projects and sloooowwwwllly upgrading them all :-)

**Pull request merged**
