### PR TITLE
Update desired_nonexistent_pages.md

### PR DESCRIPTION
**Pull request by kim12100**
I would like to write about KNN in machine learning. Would  you mind removing KNN from the list? 

Thank you! 

Woocheol

### CODE REVIEW

**Comment by NickCH-K** [comment]
Typically we'd wait until the page is ready to remove it, but if you think yours will be ready soon we can remove it ahead of time. When will yours be ready?

**Comment by kim12100** [comment]
It will be ready by today, say by this afternoon. Could you tell me how and where I should write a page?  Thank you!

**Comment by NickCH-K** [comment]
See this page for guidance: https://lost-stats.github.io/Contributing/Contributing.html

**Comment by kim12100** [comment]
Thank you!

**Comment by kim12100** [comment]
I commit and pull my file but could not push with an error message. How could I upload my page? Thank you!

**Comment by NickCH-K** [comment]
You can't push to the master branch unless you're a main contributor. Instead, push to your forked version and the make a pull request.

**Comment by kim12100** [comment]
Would you mind pulling my md.file named Nearest_Neighbot.md? Thank you!

**Comment by NickCH-K** [comment]
I can't do that from my end. A pull request is an official Git action. Go to your forked repository, click on Pull Requests, then New Pull Request, and request that your changes be merged in.

**Pull request closed without merging**
