### PR TITLE
Add Julia language to Cross-Tabulation page

### PR DESCRIPTION
**Pull request by gabriel-fallen**
I mostly followed the Python version.

### CODE REVIEW

**Comment by gabriel-fallen** [comment]
If you could also add a `hacktoberfest-accepted` tag to this PR that would be super nice from your side. 😸

**Comment by NickCH-K** [comment]
This looks great! Could you edit it to load the file from URL instead of having users download the file? Then it will be ready.

I don't know how to add tags but I will figure it out

**Comment by gabriel-fallen** [comment]
> This looks great! Could you edit it to load the file from URL instead of having users download the file? Then it will be ready.

I interpreted "Data" section of ["Implementations" section of the Contributing guide](https://lost-stats.github.io/Contributing/Contributing.html#implementations) in a sense that working with local data files is encouraged. Sure thing I'll edit to download from a URL, but Contributing might need editing too to clarify this aspect. 😺

> I don't know how to add tags but I will figure it out

I meant "label", sorry. 😅 Labels are assigned from the panel on the right of this page, under "Reviewers" and "Asignees".

**Comment by NickCH-K** [comment]
Thank you! Does the way I just added the label work? Lmk and I'll merge.

**Comment by gabriel-fallen** [comment]
@NickCH-K thanks a lot! The label works as intended, please do merge! 😄

**Pull request merged**
