### PR TITLE
Add Julia tutorial for AR(p) model estimation

### PR DESCRIPTION
**Pull request by gionikola**

### CODE REVIEW

**Comment by gionikola** [comment]
I can gradually start adding Julia sections to other time series pages as well if this one is well-received. Let me know!

**Comment by NickCH-K** [comment]
> I can gradually start adding Julia sections to other time series pages as well if this one is well-received. Let me know!

Absolutely! That would be fantastic. This is great.

**Comment by grantmcdermott** [comment]
Happy to vouch for @gionikola. 

Gio, I added you as a contributor, so you can directly edit the docs if you'd prefer that than always going through PRs (though PRs are still a good idea ofc).

**Comment by gionikola** [comment]
Thanks @grantmcdermott ! That should come in handy.

**Pull request merged**
