### PR TITLE
Added the page "Graph Themes"

### PR DESCRIPTION
**Pull request by clairefield**
I have created a page for Graph Themes in R; please let me know if I need to change anything about this page. I touched on ggplot themes, ggthemes, and modifying themes using theme() and element(). I also included links to the websites I used or thought were helpful.

### CODE REVIEW

**Comment by NickCH-K** [comment]
Looks good as a start. A few notes:

1. A lot of the code is just adding the different packaged themes to the same graph. Since we can't actually see the output (which is a good idea, we wouldn't want 30-odd graphs here), this isn't much different from just listing them. Maybe show one example of how to add a theme to a graph, list a few other good options and mention when you might want to use those specific options, and link out to a gallery for the rest.
1. For `theme()`, you should point out that it can be added on top of an already-existing prepackaged theme to further modify it
1. May be worth pointing out what a theme *can* affect (axis style, text style, etc.) and what it *can't* (selecting colors, linetypes, etc., for your geometry even though it seems like that would be "theming").
1. Sort of sounds like **ggthemes** is the only package with themes. May want to mention a few others and hint that there are still more - **hrbrthemes**, **ggpubr**, etc.

**Comment by NickCH-K** [comment]
Yes, push to the fork again and I'll see it

**Comment by clairefield** [comment]
I have committed the changes to the page Graph Themes, please let me know if I need to change anything else.

**Comment by NickCH-K** [comment]
Thank you!

**Pull request merged**
