### PR TITLE
sankey_diagrams_1

### PR DESCRIPTION
**Pull request by rmfox**

### CODE REVIEW

**Comment by NickCH-K** [comment]
Hi Ryan!

A couple changes before I can put this up

1. These pages are supposed to be language-agnostic outside of the individual-language implementations. Everything before the "implementations" section should be about Sankey diagrams in general, not about R implementations specifically
2. The site won't actually run the code or produce graphs for you. Could you upload the images as well? I see the ! image syntax linking to them but the files aren't in this PR
3. This is minor but since this is .md and not .rmd, stuff like figure-width settings in chunks won't work, and it's just r not {r}

Thanks!

**Comment by rmfox** [comment]
Hi Nick!
Thanks for the feedback. I think I've made all the necessary changes and added the files.
Thanks!
Ryan

**Comment by NickCH-K** [comment]
This looks great! I made some minor changes. Could you provide the NBA.csv syntax file? Otherwise people will not be able to run the code examples.

**Comment by rmfox** [comment]
OK, just uploaded the csv. Thanks!

**Comment by NickCH-K** [comment]
Thank you!

**Pull request merged**
