### PR TITLE
Julia implementation for ANNs page

### PR DESCRIPTION
**Pull request by gabriel-fallen**
I've added Julia implementation that mostly corresponds to the Python one but more explicit.

### CODE REVIEW

**Comment by NickCH-K** [comment]
Great, thank you very much! Again, let me know about the tag and I'll merge.

**Comment by gabriel-fallen** [comment]
@NickCH-K I'm glad to know you find my contribution useful! I though about these two as a kinda warm up and considering levelling up to more substantial ones.

**Comment by NickCH-K** [comment]
Awesome! And thank you

**Comment by gabriel-fallen** [comment]
@NickCH-K you're very welcome! 😸 Thanks for accepting.

I was also thinking about adding an example of how to move everything to a GPU, do you think that would be useful and aligned with the gist of LOST?

**Comment by NickCH-K** [comment]
I could see that going under Other, sure.

**Comment by gabriel-fallen** [comment]
In reality that would look like
```
using CUDA

gpu_model = gpu(model)
gpu_train_data = gpu(train_data)
ps = gpu(Flux.params(gpu_model)

Flux.train!(loss, ps, eachobs(gpu_train_data), opt)
```
so that's a small addition to existing example (which is the point).

Thus I don't think it's worth extraction to Other section. OTOH even ANNs are pretty tangential to __Statistical Techniques__ and training on GPU is even further away, so I have no issues with just dropping this part.

That's why I decided to consult with you before writing the code, to align with the overall logic behind LOST. 😺

**Comment by NickCH-K** [comment]
Oh I see. Yes, maybe add that as an additional step to the existing example.

On Oct 31, 2022 9:24 AM, Alexander Chichigin ***@***.***> wrote:

In reality that would look like

using CUDA



gpu_model = gpu(model)

gpu_train_data = gpu(train_data)

ps = gpu(Flux.params(gpu_model)



Flux.train!(loss, ps, eachobs(gpu_train_data), opt)



so that's a small addition to existing example (which is the point).

Thus I don't think it's worth extraction to Other section. OTOH even ANNs are pretty tangential to Statistical Techniques and training on GPU is even further away, so I have no issues with just dropping this part.

That's why I decided to consult with you before writing the code, to align with the overall logic behind LOST. 😺

**Comment by gabriel-fallen** [comment]
OK, I'll prepare actually working code example then, make another PR, and we can see and decide if it fits. 👍

**Comment by NickCH-K** [comment]
To be clear I think it would make sense to keep what you already have, but then have an addendum that alternately puts the calculations on the gpu

On Oct 31, 2022 10:05 AM, Alexander Chichigin ***@***.***> wrote:

OK, I'll prepare actually working code example then, make another PR, and we can see and decide if it fits. 👍

**Comment by gabriel-fallen** [comment]
@NickCH-K yep, that was the idea. 😸

**Pull request merged**
