### PR TITLE
Regex branch

### PR DESCRIPTION
**Pull request by Matt-McCoy**
I wanted to try and make a page for Regular expressions

### CODE REVIEW

**Comment by aeturrell** [comment]
Great idea to add regex! One comment from my quick look: my view is it's best to keep the "keep in mind" and "also consider" parts language-agnostic when possible.

**Comment by NickCH-K** [comment]
A regex page is definitely a welcome addition. Agreed that Keep in Mind and Also Consider should be language-agnostic. 

While we're certainly not going to squeeze all regex onto a single page, some valuable additions would be:

- Matching sets of characters (i.e. `[A-Za-z]` or `[0-9]`)
- A bit more detail on `*`, for example its use with `?` or with things other than `.`
- Subexpressions, i.e. `stringr::str_replace('*My RMarkdown Title*', '\\*(.*?)\\*', '# \\1')`

I'm happy to add these if you don't want to.

**Comment by aeturrell** [comment]
I actually just added a page on regex to work-in-progress jupyter book [here](https://aeturrell.github.io/coding-for-economists/text-intro.html) and very happy to add bits that we think are most important or to steal any other bits we think could be good for this page. There's a lot one could have on regex!

**Comment by Matt-McCoy** [comment]
Thank you for letting me know, i'll make sure to keep those sections language-agnostic. I'll go back and include more information on the regex syntax and their interactions as well.

**Comment by khwilson** [comment]
This is great! Some suggested Python text below:


## Python

In Python, regular expressions are implemented in the [`re`](https://docs.python.org/3/library/re.html) module or, alternatively, through the `.str` interface in `pandas`. Let's go through a few examples:

If we want to search for all words that started with the characters "ab" we would use the character `^` to specify we want words that start with "ab".

```python
import re

strings = ["abcd", "cdab", "cabd", "c abd"]
filtered_strings = [s for s in strings if re.search(r"^ab", s)]

print(filtered_strings)
# ['abcd']
```

Some notes about this example:
* We've used the `re.search` function. Sometimes people instead use [`re.match`](https://docs.python.org/3/library/re.html#search-vs-match). `re.match` only looks for matches at the _beginning_ of strings, so the functions `re.search(r"^ab", s)` and `re.match(r"ab", s)` are equivalent.
* You'll notice that instead of using plain double quotes around our regular expression we used the pattern `r"^ab"`. The `r` means "raw string", and it turns off (almost) all escaping. Thus, `r"\d"` and `"\\d"` are equivalent. Because of the how common `\` is in regular expressions, it's usually wise to use raw strings for regular expressions to avoid confusing errors.

Alternatively, we could use also implement the above example with pandas:

```python
import pandas as pd

df = pd.DataFrame({"strings": ["abcd", "cdab", "cabd", "c abd"]})
df[df["strings"].str.contains(r"^ab", regex=True)]
```

If we instead want to _replace_ the text that matches a regular expression, we can use the `re.sub` or pandas `.str.replace`:

```python
import re

import pandas as pd

strings = ["what", "why", "you", "blazers", "fire", "hello"]

# Replace all the vowels in strings containing a vowel with "!"
changed_strings = [
    re.sub(r"[aeiou]", "!", s)
    for s in strings
    if re.search(r"[aeiou]", s)
]
print(changed_strings)
# ['wh!t', 'y!!', 'bl!z!rs', 'f!r!', 'h!ll!']

# Do the same thing in pandas
df = pd.DataFrame({"strings": strings})
changed_series = df.loc[
    df["strings"].str.contains(r"[aeiou]", regex=True),
    "strings"
].str.replace(r"[aeiou]", "!", regex=True)
print(changed_series)
# 0       wh!t
# 2        y!!
# 3    bl!z!rs
# 4       f!r!
# 5      h!ll!
# Name: strings, dtype: object
```

**Comment by NickCH-K** [comment]
Made some minor style changes and added the Python. Adding now! Thanks for this.

**Pull request merged**
