### PR TITLE
Propensity Score Matching

### PR DESCRIPTION
**Pull request by JonasBowman**
@grantmcdermott here is my pull request for PSM

### CODE REVIEW

**Comment by NickCH-K** [comment]
The content looks good! Some notes:

1. We can't use RMDs (or knitted MD output from RMDs), only regular MD. This shouldn't take much conversion - see the [New Page Template](https://github.com/LOST-STATS/lost-stats.github.io/edit/source/NewPageTemplate.md) or one of  the other completed .MD files in the repo.
2. That's a lot of regression tables in the output! You could probably cut most/all of them.
3. The [current lit](https://ideas.repec.org/a/cup/polals/v27y2019i04p435-454_00.html) recommends that propensity scores be used with inverse probability weighting rather than matching. I think it's okay to leave in a matching method but you should probably also show IPW and note the recommendation, see some example code [here](https://theeffectbook.net/ch-Matching.html?panelset3=r-code4#panelset3_r-code4).

**Comment by JonasBowman** [comment]
I tried to incorporate all of the changes you suggested, let me know if there are more edits I should make!

**Comment by NickCH-K** [comment]
Made a buncha changes, looks good! Merging as soon as the checks complete.

**Comment by JonasBowman** [comment]
Thank you! 

Jonas Bowman

**Pull request merged**
