### PR TITLE
Create importing_delimited_files

### PR DESCRIPTION
**Pull request by clibassi**
Fires time writing a new page, so hope I got this right. For some reason the preview pane was rendering the same as the raw, so I may have missed something here and there.

### CODE REVIEW

**Comment by NickCH-K** [comment]
Great! Added R and made some minor changes.

The only note is that the code is based on having the file saved on the local machine. Generally we have files stored on the GitHub and point the code to the URL of the file - is there a particular reason that wouldn't be a good approach here?

If not, I can upload the file appropriately and change the local file calls to URLs (assuming Julia doesn't have a problem with that, that's the only one I don't know)

**Comment by clibassi** [comment]
Nope - that totally works. Apologies - I was just going on instinct about which type of imports to provide guidance on. Didn't realize we had a standard way for doing data imports.

My only small thought is that it might be good to have explicit examples for true beginners of how to read data off of your local machine, but maybe we assume more knowledge for these tutorials. But I trust you all have thought through this more than I have.
________________________________

**Comment by NickCH-K** [comment]
Sounds good. Probably a few days before I can get to this but I'll make those changes.

**Comment by NickCH-K** [comment]
Ended up keeping both!

**Pull request merged**
