### PR TITLE
Update to Other/import_a_foreign_data_file.md

### PR DESCRIPTION
**Pull request by mcwayrm**
Made a small contribution to the R code commands in Other/import_a_foreign_data_file.md. 
`rio` is a general purpose package to import a variety of different file types smoothly. 
- small note that there were several staged commits forked from the upstream (source) that were pushed when I pushed my commit. These were not done my me. My contributions are 58a5ab2 and 715f824.

### CODE REVIEW

**Comment by NickCH-K** [comment]
This looks good! I can't merge until the build and push passes, but I don't think that's to do with your work, rather a Ruby thing. I'll merge once that gets cleared up on our end.

**Comment by mcwayrm** [comment]
Got it! Should I wait to start on making edits on another page until this is resolved (then pull the updated repo)? Or should I continue to make pull requests despite not clearing the check?

**Comment by NickCH-K** [comment]
You can keep going, although we won't be able to merge anything until we resolve the Ruby issue.

**Comment by NickCH-K** [comment]
Alright! I think we have fixed the Ruby problem. Still getting a build error on your PR but I suspect it's a versioning issue. Can you try syncing your fork and re-pushing?

**Comment by mcwayrm** [comment]
Great!, I just did `git pull upstream source` and `git push`. Submitting the PR now. I didn't make any other edits. Hopefully this works. If not, I think I can recall the few changes I made and start with a fresh fork of the repo and try adding that in as a new PR.

**Comment by mcwayrm** [comment]
Most recent PR commit HEAD should be `759a46039b33388adf0666dbb2469cddfede8c8e`

**Comment by NickCH-K** [comment]
Awesome! First new commit for a while, due to this Ruby thing.

**Comment by mcwayrm** [comment]
Great! Now that I know the commits will merge well I will try to make periodic/consistent additions. Hoping to maintain the stamina.

**Pull request merged**
