### PR TITLE
Update collapse_a_data_set.md

### PR DESCRIPTION
**Pull request by clibassi**

### CODE REVIEW

**Comment by NickCH-K** [comment]
This looks great, but the description says you can download the file at "the site" but doesn't give a full url. Could you add it?

**Comment by clibassi** [comment]
I modified the wording a bit to make it more clear that I was referring to the file available at the link in the previous sentence. Unfortunately, all I can do is link to the site, not the CSV directly, since Kaggle seems to hide those direct links behind some HTML I don't understand.

**Comment by NickCH-K** [comment]
Oh I see now, makes sense. Thanks!

**Comment by grantmcdermott** [comment]
Just to say: I think we should stick a consistent set of operations across all languages. So, the same set of operations performed on exactly the same data. It's okay, say, if a particular dataset doesn't show off gtools speed advantages over regular Stata. The point is to convey syntax and equivalency of operations.

With that in mind, @clibassi  would you consider updating the post to use the same `storms` dataset? You can pull the CSV directly from the web as in the Python example. I also think showing how to combine several collapse operations (i.e. first in addition to mean) as with the other langs would be helpful.

**Comment by clibassi** [comment]
Sure thing - will do.

**Comment by clibassi** [comment]
I assume it's okay if I also modify the traditional collapse example that was already in place before I added the gcollapse part?

**Comment by grantmcdermott** [comment]
Ya, perfect. Thanks!

(Also, I think you're missing closing backticks in the bottom chunk.)

**Pull request merged**
