### PR TITLE
Propensity Score Matching Page

### PR DESCRIPTION
**Pull request by claireconglizhang**
Propensity score matching is a very useful method. Just wanted to start this page so we could have more great collaborators to add onto this important topic. Feel free to let me know if you have any questions!

### CODE REVIEW

**Comment by NickCH-K** [comment]
Seems like a good start (although quite a few of the PSM methods listed in Also Consider aren't PSM). I'll wait until we have at least one application to merge though

**Comment by claireconglizhang** [comment]
Thank you for taking time to look at it and for the great feedback! I’ll continue working on it and add some applications.

**Comment by grantmcdermott** [comment]
Hey @claireconglizhang following up on the status here. Can you add at least one application example please. 

It's fine if you copy from the resource that you mention on the page as long as you give them credit (which you already have).

**Comment by claireconglizhang** [comment]
My apologies and thank you for the reminder, Professor McDermott. I had a pretty hectic spring break driving my son to visit a couple of colleges he’s been accepted into. I’m back home tonight and will get my hands on the unfinished project soon but with a GE work coming in tomorrow, I think my best prediction is to finish this LOST project by Tuesday night. Thank you for the understanding. I’ll keep you posted.

 

Claire

**Comment by claireconglizhang** [comment]
Hi,

I added an R application to this page and also the data and my code file just in case. Please let me know if it can be any of use. I'm glad to continue working on it if needed.

Thanks to all,
Claire

**Comment by claireconglizhang** [comment]
Ooops. Forgot the ggthemes package.

**Comment by NickCH-K** [comment]
Filled wiht bc8310c

**Pull request closed without merging**
