### PR TITLE
Create Dif in Dif model estimate 

### PR DESCRIPTION
**Pull request by zuzhangjin**

### CODE REVIEW

**Comment by NickCH-K** [comment]
This is great. I will work on bringing it in soon. I may change the name to being specific to 2x2 DIDs, since that's what you have here (a treatment rollout DID would probably want the did package)

**Comment by NickCH-K** [comment]
Alright! I've just gone through and made some changes throughout for style consistency, and also there were some bugs in the code.

Could you please:

1: Provide the data you were working with? Otherwise, readers won't be able to use your example code
2: The line 
DiD <- mutate(DiD, treat = DiD$year>=2010 & DiD$year<=2013)
is incorrect. This should be specifying which states are treated. What is the correct list of states to use here?

**Comment by zuzhangjin** [comment]
Hi Nick,
Thank you for letting me know.

The data has an indicator to show it is treatment or control, it does not have any states information. I will attach the data to attachment. It actually comes from EC510  and the professor cleaned the data which only contain limited information: murder rate, year and treated or not .
if you have any concerns please let me know.

Thank you very much!
________________________________

**Comment by NickCH-K** [comment]
Hi again,

I don't see any attached data - I don't think you can email an attachment to GitHub. If you come to this discussion page directly ( https://github.com/LOST-STATS/lost-stats.github.io/pull/38 ) I believe you can upload data, though.

**Comment by zuzhangjin** [comment]
Here is the data
[did_crime.xlsx](https://github.com/LOST-STATS/lost-stats.github.io/files/4775848/did_crime.xlsx)

**Comment by zuzhangjin** [comment]
Thank you for letting me know.
 I just upload the data to the discussion page. Sorry for any inconvenience.




Zuzhang Jin
________________________________

**Comment by NickCH-K** [comment]
Thank you! Merging now, I'll fix the rest of the code issues afterwards

**Pull request merged**
