### PR TITLE
Create Styling Scatterplots 

### PR DESCRIPTION
**Pull request by FeiyiShao**

### CODE REVIEW

**Comment by NickCH-K** [comment]
This is great! There's some fixes I'll need to make when I bring it in but that's fine.

I want to confirm this is ready to go before I bring it in -I noticed there have been a bunch of changes since the initial PR. Just let me know.

**Comment by FeiyiShao** [comment]
> This is great! There's some fixes I'll need to make when I bring it in but that's fine.
> 
> I want to confirm this is ready to go before I bring it in -I noticed there have been a bunch of changes since the initial PR. Just let me know.

**Comment by FeiyiShao** [comment]
Yes, I think it is ready to go. Thank you so much for help.

**Comment by NickCH-K** [comment]
Great! I will look at this tomorrow.

**Comment by FeiyiShao** [comment]
Thank you for doing that.

**Pull request merged**
