### PR TITLE
Dummy vars

### PR DESCRIPTION
**Pull request by ethanholdahl**

### CODE REVIEW

**Comment by grantmcdermott** [comment]
Thanks @ethanholdahl. Couple changes that I'd like you to make:

- Please mention the `as.factor()` short-cut for automatically parsing categorical variables as dummies in R regression models (Stata and other SW langs have similar capabilities). This is important to emphasise  -- probably in the ["Keep in mind"](https://lost-stats.github.io/Contributing/Contributing.html#keep-in-mind) section of the page -- since it means you may not even need to create dummy variables as long as you specify your categorical variables as factors.
- Speaking of which, the factor to dummy matrix conversion (i.e. contrast function) in R is done via a call to `model.matrix()`. E.g. `model.matrix(~ 0 + iris$Species)`.
- However, note that the `model.matrix(~0+iris$Species)` call above will create separate dummy columns for *all* category levels of the Species variable. This is often referred to as **one hot encoding**; a phrase that is esp. common in the machine learning literature and something that you should probably mention in the "Keep in mind" section too.
- The problem with one hot encoding (at least for traditional regression frameworks) is that it falls into the **dummy variable trap**; another concept that you should probably mention. So you need to manually exclude, say, the first column from the model.matrix object.
- If you don't like the manual option of excluding one factor level, then there are several packages that can do this for you. (See [here](https://stackoverflow.com/questions/48649443/how-to-one-hot-encode-several-categorical-variables-in-r).) One example using the [**recipes**](https://tidymodels.github.io/recipes/articles/Dummies.html) package would be: `recipe( ~ ., data = iris) %>% step_dummy(Species) %>% prep() %>% juice()`.

**Comment by ethanholdahl** [comment]
Sure thing. I'll commit those changes by tonight.

**Comment by NickCH-K** [comment]
Sorry to ask for more changes, but can you add code that takes a categorical variable and turns it into a dummy in the data for each level of the categorical variable? In R this can be done with `model.matrix` or `sjmisc::to_dummy()`. In Stata it's `xi i.` Not sure about Matlab. I think this is what most people would be looking for when they go to a page about creating dummy variables.

**Comment by ethanholdahl** [comment]
Sure thing, I'll add it to the implementation section.

**Comment by NickCH-K** [comment]
Awesome! Thank you very much, merging now

**Pull request merged**
