### PR TITLE
upload the data

### PR DESCRIPTION
**Pull request by ShanZhang5**
[geo2_br2010.zip](https://github.com/LOST-STATS/lost-stats.github.io/files/4301123/geo2_br2010.zip)
[GlobalGWRwUni_PM25_GL_201001_201012-RH35_Median_NoDust_NoSalt.nc.zip](https://github.com/LOST-STATS/lost-stats.github.io/files/4301125/GlobalGWRwUni_PM25_GL_201001_201012-RH35_Median_NoDust_NoSalt.nc.zip)

### CODE REVIEW

**Comment by ShanZhang5** [comment]
Hi Nick,

I just did another PR for the data. I initially wanted to contain all my data in one folder and zip it but it wouldn't let me upload it since it is too big(over 10Mb). So I uploaded them separately.

And nc file is not allowed to be uploaded so I zipped it.

Let me know if this is working?


Thank you.


Shan

**Comment by NickCH-K** [comment]
We want the examples to be runnable using the code provided, but I'll see what I can do about adding unzipping to the R code.

**Comment by NickCH-K** [comment]
Alright, I've got the data files loaded and the code updated to reflect their location (unfortunately for some reason the R code won't load the files from GitHub so the instructions require them to be downloaded first).

I can't run the code, my computer isn't powerful enough. Could you please check the edits I've made and make sure it still runs properly? Thank you: https://lost-stats.github.io/Geo-Spatial/merging_shape_files.html

**Comment by ShanZhang5** [comment]
Hi Nick,
I just checked your edits and it runs properly.
It does need a powerful computer bc the nc file is a very high resolution data. But it will work fine in google computing engine.
Hopefully this will be helpful some people.


Thank you!

Shan

**Pull request closed without merging**
