### PR TITLE
Code Sample Tester

### PR DESCRIPTION
**Pull request by khwilson**
When I'm on vacation, I relax by doing pure engineering work instead of my usual management work, so I took a stab at #8.

This PR sets up an automated testing pipeline for code samples. Specifically, it sets up a `py.test` runner that searches for all the code blocks in the repository and then attempts to run the python and r ones in an appropriate docker image. Fail the test if the code block doesn't complete.

These are attached to docker images currently housed in my personal repository space while I work out how to get a machine user setup to build these.
    
Note that these tests currently take a _long_ time to run and a _lot_ of them fail. The reasons for failure are mostly:
    * An uninstalled dependency in the dockerfile
    * A code block that is separated by raw markdown.
    
In the latter case, I've added a feature where you can tell the parser that two code blocks should be run sequentially in the same instance by adding a ?example=id tag to the language name. This format is necessary due to the fact that we use Rouge as our lexer/syntax highlighter.

Anyway, try it out with the README's new instructions. :-)

### CODE REVIEW

**Comment by NickCH-K** [comment]
This is great! Is there a way to set some chunks to not be tested? I think some of the examples, eg in the geospatial section, link out to a large dataset to be downloaded, or take a long time to run.

**Comment by khwilson** [comment]
Sure! There's now an `--xmdpath` option that excludes paths.

**Comment by khwilson** [comment]
Also, thinking about it more, you could add an option like `python?example=id&skip=true` or something for permanent skipping.

**Comment by aeturrell** [comment]
This is so impressive and useful. I don't have much to add except, if it would speed things up, couldn't R and Python be in the same docker image?

**Comment by khwilson** [comment]
The R image unfortunately takes about 30min to build whereas the python image takes about 1 minute, so I don't think that separating them will actually speed things up. :-)

Plus, the Python image is about 1.3GB whereas the R image is about 2.2GB, so combining them would just keep blowing them up. :-)

**Comment by grantmcdermott** [comment]
Amazing @khwilson. Quickly on the docker builds; I guess it's possible, but 30min seems way too long of a build time for the R container. Do you mind sharing your dockerfile with me? There are a couple base containers worth using that automatically pull in package binaries instead of building from source, etc. Makes everything much much quicker.

**Comment by aeturrell** [comment]
I did hear about the version of mamba (itself a faster conda) for R called rhumba that tries to solve this problem: https://github.com/mamba-org/rhumba

However, I think it’s early days for this project so not sure how stable it is yet.

**Comment by khwilson** [comment]
The images are currently at github.com/khwilson/lost-docker-images (it’s a
public repo) and I’ll move them soon to the lost-stats org.

I was trying to avoid most of the base docker images because I specifically
wanted to end up with a lock file. Currently renv seems to be the way to go
there and I couldn’t figure out how to get it to pull binaries.

But if you can pull them, that would be great! Also happy to be overruled
on the better base R image!

**Comment by khwilson** [comment]
Okiedokes, the docker images are here now: https://github.com/LOST-STATS/docker-images

**Comment by khwilson** [comment]
Hi everyone! Per our earlier discussion today, if someone wants to make sure I haven't borked any particular page, then this is the auto tester. It still works, and I've fixed the errors in about 100 of the currently 163 Python and R examples. :-)

**Comment by NickCH-K** [comment]
Awesome! So it's ready to merge then?

**Comment by NickCH-K** [comment]
Great! I wasn't able to figure out earlier from the build job how to see the failing examples. Where are they?

**Comment by khwilson** [comment]
Now that this has appeared, they should appear here: https://github.com/LOST-STATS/lost-stats.github.io/runs/2501926797?check_suite_focus=true

I may need to experiment a bit b/c this only gets so much space and RAM, so this is just the python tests to start.

**Pull request merged**
