### PR TITLE
add stepwise regression

### PR DESCRIPTION
**Pull request by Pengfei1005**

### CODE REVIEW

**Comment by Pengfei1005** [comment]
add stepwise regression

**Comment by NickCH-K** [comment]
Very nice addition. Some notes:

- All the Also Consider entries are more Keep in Mind entries and so should be moved there
- In their place you should probably mention penalized regression / LASSO (https://lost-stats.github.io/Machine_Learning/penalized_regression.html) which is another model-selection method
- The output tables are included in the code chunks even though they're not code. This will make the code chunks not work. Either take the output tables out of code chunks and into the text, delete them, or make them into comments in the code
- This is a super long writeup given all the results tables. Maybe find a way to trim it down. We definitely don't need the full results from each step for *every* method. Maybe just a walkthrough for one, with a note on how to change the code to get the others. And even for that one we probably don't need every output table.

**Comment by NickCH-K** [comment]
Added

**Comment by Pengfei1005** [comment]
@NickCH-K Thanks a lot!!!

**Pull request closed without merging**
