### PR TITLE
Interaction terms and polynomials in Julia

### PR DESCRIPTION
**Pull request by gabriel-fallen**
I've added Julia examples that closely follow R and Python ones.

Once again I would greatly appreciate it if you'd add the `hacktoberfest-accepted` label to the PR. 😸

### CODE REVIEW

**Comment by NickCH-K** [comment]
Thank you! Looks good.

**Comment by gabriel-fallen** [comment]
@NickCH-K Thanks a lot!

Have you looked at the comments I wrote in the code snipped? Are the style and the content OK? I tried to explain some finer points for someone not intimately familiar with Julia or stats, but I have no idea if I make sense...

**Comment by NickCH-K** [comment]
I read the whole thing - looks fine to me! Curious about the differences in how collinear variables are dropped or not.

**Comment by gabriel-fallen** [comment]
> Curious about the differences in how collinear variables are dropped or not.

That's some default built-in behaviour of the `GLM` Julia package. I don't think I can explain it any better than I already did at this point... 😅

**Pull request merged**
